<a href="https://colab.research.google.com/github/er-knight/using-python-for-research/blob/main/week-2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### [`numpy`](https://numpy.org/)

In [ ]:
import numpy as np

np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]]) # by convention, multi-dimensional array names are uppercase
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[1, :] # second row

array([4, 5, 6])

In [ ]:
A[:, 1] # second column

array([2, 5])

In [ ]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y # matrix addition

array([5, 7, 9])

In [ ]:
z = np.array([1, 2, 3, 4, 5, 6])
i = np.array([0, 2, 4]) # indices

z[i]

array([1, 3, 5])

In [ ]:
z > 4 # element greater than 4 are True and others are False

array([False, False, False, False,  True,  True])

In [ ]:
i = z > 4 # indices where element is greater than 4
z[i] # logical indexing

array([5, 6])

In [ ]:
np.linspace(1, 100, 10) # linearly spaced 10 numbers from 1 to 100

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
np.logspace(np.log10(10), np.log10(100), 10) # logarithmically spaced 10 numbers from log10(10) to log10(100)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [ ]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y.shape

(3, 3)

In [ ]:
Y.size # number of elements in Y

9

In [ ]:
r = np.random.random(10) # 10 random numbers
r

array([0.10431749, 0.69100828, 0.63907706, 0.1852429 , 0.53850186,
       0.92359282, 0.27708   , 0.75984439, 0.37878407, 0.35179695])

In [ ]:
np.any(r > 0.9)

True

In [ ]:
np.all(r <= 0.1)

False